// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./components/Footer/index.vue')['default']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonClose: typeof import('~icons/carbon/close')['default']
    IconCarbonHome: typeof import('~icons/carbon/home')['default']
    IconCarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconEpElemeFilled: typeof import('~icons/ep/eleme-filled')['default']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    Logo: typeof import('./components/Logo/index.vue')['default']
    MainView: typeof import('./components/MainView/index.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    NLayout: typeof import('naive-ui')['NLayout']
    PageHeader: typeof import('./components/PageHeader/index.vue')['default']
    SiderMenu: typeof import('./components/SiderMenu/index.vue')['default']
  }
}

export { }
