// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddNode: typeof import('./components/scWorkflow/nodes/addNode.vue')['default']
    Approver: typeof import('./components/scWorkflow/nodes/approver.vue')['default']
    Branch: typeof import('./components/scWorkflow/nodes/branch.vue')['default']
    ColumnSetting: typeof import('./components/scTable/columnSetting.vue')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonClose: typeof import('~icons/carbon/close')['default']
    Logo: typeof import('./components/Logo/index.vue')['default']
    MainView: typeof import('./components/MainView/index.vue')['default']
    Multiple: typeof import('./components/scUpload/multiple.vue')['default']
    My: typeof import('./components/scFilterBar/my.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    NodeWrap: typeof import('./components/scWorkflow/nodeWrap.vue')['default']
    PageHeader: typeof import('./components/PageHeader/index.vue')['default']
    Promoter: typeof import('./components/scWorkflow/nodes/promoter.vue')['default']
    PySelect: typeof import('./components/scFilterBar/pySelect.vue')['default']
    ScContextmenu: typeof import('./components/scContextmenu/index.vue')['default']
    ScContextmenuItem: typeof import('./components/scContextmenu/scContextmenuItem.vue')['default']
    ScCropper: typeof import('./components/scCropper/index.vue')['default']
    ScDialog: typeof import('./components/scDialog/index.vue')['default']
    ScEcharts: typeof import('./components/scEcharts/index.vue')['default']
    ScEditor: typeof import('./components/scEditor/index.vue')['default']
    ScFileSelect: typeof import('./components/scFileSelect/index.vue')['default']
    ScFilterBar: typeof import('./components/scFilterBar/index.vue')['default']
    ScForm: typeof import('./components/scForm/index.vue')['default']
    ScFormTable: typeof import('./components/scFormTable/index.vue')['default']
    ScIconSelect: typeof import('./components/scIconSelect/index.vue')['default']
    ScPageHeader: typeof import('./components/scPageHeader/index.vue')['default']
    ScSelect: typeof import('./components/scSelect/index.vue')['default']
    ScStatistic: typeof import('./components/scStatistic/index.vue')['default']
    ScStatusIndicator: typeof import('./components/scMini/scStatusIndicator.vue')['default']
    ScTable: typeof import('./components/scTable/index.vue')['default']
    ScTableSelect: typeof import('./components/scTableSelect/index.vue')['default']
    ScTitle: typeof import('./components/scTitle/index.vue')['default']
    ScTrend: typeof import('./components/scMini/scTrend.vue')['default']
    ScUpload: typeof import('./components/scUpload/index.vue')['default']
    ScVideo: typeof import('./components/scVideo/index.vue')['default']
    ScWorkflow: typeof import('./components/scWorkflow/index.vue')['default']
    Select: typeof import('./components/scWorkflow/select.vue')['default']
    Send: typeof import('./components/scWorkflow/nodes/send.vue')['default']
    SiderMenu: typeof import('./components/SiderMenu/index.vue')['default']
    Tableselect: typeof import('./components/scForm/items/tableselect.vue')['default']
  }
}

export { }
