// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Footer: typeof import('./components/Footer/index.vue')['default']
    Logo: typeof import('./components/Logo/index.vue')['default']
    MainView: typeof import('./components/MainView/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    PageHeader: typeof import('./components/PageHeader/index.vue')['default']
    SiderMenu: typeof import('./components/SiderMenu/index.vue')['default']
  }
}

export { }
